---
abstract: ~
author:
  - 'Takatoshi Kitano <kitano.tk at gmail.com> '
build_requires:
  Test::Builder: 0
  Test::Class: 0
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.720'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CHI-Driver-MemcachedFast
no_index:
  directory:
    - inc
    - t
requires:
  CHI: 0.081
  CHI::Driver::Memcached: 0
  Cache::Memcached::Fast: 0
  perl: 5.6.0
version: 0.02
